FROM centos

LABEL version=1.0
LABEL description="This is an apache image"
LABEL vendor=fmediotte

RUN yum install httpd -y

WORKDIR /var/www/html

COPY startbootstrap-freelancer-master .

ENV contenido prueba

RUN echo "$contenido" > /var/www/html/prueba.html

CMD apachectl -DFOREGROUND
